### ISSUE TITLE
Type of change for updates made at section level

### ISSUE THREAD

**Issue by Aniformer** [usgpo/api#38] opened 2019-04-19 10:36 UTC
Hi team,
https://www.federalregister.gov/api/v1/documents/2018-28281.json
In the above API endpoint the 'action' key gives us whether the entire FR document is a rule or a proposed rule. 

But as noticed in the particular ecfr link for that FR document : https://www.federalregister.gov/documents/2019/02/14/2018-28281/regulatory-capital-rule-implementation-and-transition-of-the-current-expected-credit-losses?utm_campaign=subscription%20mailing%20list&utm_source=federalregister.gov&utm_medium=em

There are multiple updates made for each legal citation at the section level. Is their any API endpoint that could give us the type of change made for an update made for each legal citation at the section level?

Thank you,
Anirudh

**Comment by jonquandt** [comment] 2019-04-24 20:51
@Aniformer  - this appears to be a duplicate of https://github.com/usnationalarchives/federalregister-api-core/issues/15 - the FederalRegister.gov team would be best able to answer your question on this one. If I'm understanding you correctly, there is no currently no endpoint on govinfo that would give you the "type of change" at the section-level.

Something you might want to consider investigating is the bulkdata ecfr data available via the API. From this data, you could record and perform diffs against updated versions of the file to see what changes are made to the CFR based on an individual FR rule.

https://api.govinfo.gov/collections/ECFR/2019-04-17T00:00:00Z?pageSize=50&offset=0&api_key=DEMO_KEY

This would certainly be valuable functionality.

**Closed** 2019-05-21 17:10 UTC
